# Generated by Django 3.2.8 on 2021-10-21 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='fechaNacimiento',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
